language: go

go:
  - 1.2
  - 1.3
  - tip

install:
  - go get github.com/mitchellh/mapstructure
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/hypebeast/go-config/config
  - go get github.com/hypebeast/go-config/example/config
  - go get github.com/hypebeast/go-config/example
